version: "3.9"
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/work/

  influxdb:
    image: influxdb:2.6 
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: mcidaen
      DOCKER_INFLUXDB_INIT_PASSWORD: mcidaen2023
      DOCKER_INFLUXDB_INIT_ORG: mcidaen
      DOCKER_INFLUXDB_INIT_BUCKET: mod7
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mcidaen_token
      